name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1, 8.2, 8.3 ]
        laravel: [ 6.*, 7.*, 8.*, 9.*, 10.* ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: 6.*
            testbench: 4.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 8.*
            testbench: 6.*
          - laravel: 9.*
            testbench: 7.*
          - laravel: 10.*
            testbench: 8.*
        exclude:
          - laravel: 6.*
            php: 8.1
          - laravel: 6.*
            php: 8.2
          - laravel: 6.*
            php: 8.3
          - laravel: 7.*
            php: 8.1
          - laravel: 7.*
            php: 8.2
          - laravel: 7.*
            php: 8.3
          - laravel: 8.*
            php: 7.2
          - laravel: 8.*
            php: 7.3
          - laravel: 8.*
            php: 8.2
          - laravel: 8.*
            php: 8.3
          - laravel: 9.*
            php: 7.2
          - laravel: 9.*
            php: 7.3
          - laravel: 9.*
            php: 7.4
          - laravel: 9.*
            php: 8.3
          - laravel: 10.*
            php: 7.2
          - laravel: 10.*
            php: 7.3
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Set phpunit.xml
        run: cp phpunit.xml.dist phpunit.xml

      - name: Execute tests
        run: vendor/bin/pest

      - name: Store test reports
        uses: actions/upload-artifact@v2
        with:
          name: Store report
          retention-days: 1
          path: |
            ./reports
